DEBUG | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 26 | hello
ERROR | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
DEBUG | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 26 | hello
ERROR | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:27:28 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:31:16 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:31:37 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:33:06 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:34:26 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:34:36 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:34:43 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:36:02 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:36:14 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:36:41 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test2
ERROR | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:38:51 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test2
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
ERROR | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:39:50 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test2
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test2
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test2
ERROR | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test1
DEBUG | 04/16/2023 12:41:33 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test2
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test2
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 31 | APP_CONFIG_LOCATION is not present in the current environment.  Defaulting APP_CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local.
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test2
ERROR | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test1
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 28 | APP_ENVIRONMENT set to test2
DEBUG | 04/16/2023 12:42:19 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 34 | APP_CONFIG_LOCATION set to test3
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 4 | Hello
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to test
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to local
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to test
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to properties_config.ini
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to debug
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to test
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to test2
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | CONFIG_LOCATION is not present in the current environment.  Defaulting CONFIG_LOCATION to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to properties_config.ini
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to test1
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | APP_ENVIRONMENT is not present in the current environment.  Defaulting APP_ENVIRONMENT to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to local
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to test2
ERROR | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 36 | LOG_LEVEL is not present in the current environment.  Defaulting LOG_LEVEL to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to debug
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to test1
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to test2
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 19 | LOG_LEVEL set to test1
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 22 | APP_ENVIRONMENT set to test2
DEBUG | 04/16/2023 12:58:09 PM | /home/reed/dev/python-wheels/easy-read/easy_reed/_logger.py | line 25 | APP_CONFIG_LOCATION set to test3
